/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SiteConfig = {
  _id: string;
  _type: "siteConfig";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: string;
  siteUrl?: string;
  defaultSeo?: {
    title?: string;
    description?: string;
    ogImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
  nav?: Array<{
    label?: string;
    href?: string;
    _type: "navItem";
    _key: string;
  }>;
  footer?: string;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  seo?: {
    title?: string;
    description?: string;
    ogImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
  blocks?: Array<
    | ({
        _key: string;
      } & Hero)
    | ({
        _key: string;
      } & FeatureGrid)
    | ({
        _key: string;
      } & Pricing)
    | ({
        _key: string;
      } & Faq)
    | ({
        _key: string;
      } & Testimonial)
  >;
};

export type Testimonial = {
  _type: "testimonial";
  heading?: string;
  testimonials?: Array<{
    quote?: string;
    author?: string;
    role?: string;
    avatar?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _type: "testimonialItem";
    _key: string;
  }>;
};

export type Faq = {
  _type: "faq";
  heading?: string;
  items?: Array<{
    question?: string;
    answer?: string;
    _type: "item";
    _key: string;
  }>;
};

export type Pricing = {
  _type: "pricing";
  heading?: string;
  plans?: Array<{
    name?: string;
    price?: string;
    interval?: string;
    features?: Array<string>;
    highlighted?: boolean;
    ctaLabel?: string;
    ctaHref?: string;
    _type: "plan";
    _key: string;
  }>;
};

export type FeatureGrid = {
  _type: "featureGrid";
  heading?: string;
  features?: Array<{
    icon?: string;
    title?: string;
    body?: string;
    _type: "feature";
    _key: string;
  }>;
};

export type Hero = {
  _type: "hero";
  heading?: string;
  subheading?: string;
  ctaLabel?: string;
  ctaHref?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type LucideIcon = string;

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes =
  | SiteConfig
  | Page
  | Testimonial
  | Faq
  | Pricing
  | FeatureGrid
  | Hero
  | LucideIcon
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./apps/web/src/sanity/queries.ts
// Variable: SITE_CONFIG_QUERY
// Query: *[_type == "siteConfig"][0] {    ...,    nav[] {      ...,    }  }
export type SITE_CONFIG_QUERYResult = {
  _id: string;
  _type: "siteConfig";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: string;
  siteUrl?: string;
  defaultSeo?: {
    title?: string;
    description?: string;
    ogImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
  nav: Array<{
    label?: string;
    href?: string;
    _type: "navItem";
    _key: string;
  }> | null;
  footer?: string;
} | null;
// Variable: ALL_PAGE_SLUGS_QUERY
// Query: *[_type == "page" && defined(slug.current)]{    "slug": slug.current  }
export type ALL_PAGE_SLUGS_QUERYResult = Array<{
  slug: string | null;
}>;
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug][0] {    title,    seo,    blocks[] {      ...,      _type == "hero" => {        heading,        subheading,        ctaLabel,        ctaHref,        image,      },      _type == "featureGrid" => {        heading,        features[] {          icon,          title,          body,        }      },      _type == "pricing" => {        heading,        plans[] {          name,          price,          interval,          features,          highlighted,          ctaLabel,          ctaHref        }      },      _type == "faq" => {        heading,        items[] {          question,          answer        }      },      _type == "testimonial" => {        heading,        testimonials[] {          quote,          author,          role,          avatar        }      }    }  }
export type PAGE_QUERYResult = {
  title: string | null;
  seo: {
    title?: string;
    description?: string;
    ogImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  } | null;
  blocks: Array<
    | {
        _key: string;
        _type: "faq";
        heading: string | null;
        items: Array<{
          question: string | null;
          answer: string | null;
        }> | null;
      }
    | {
        _key: string;
        _type: "featureGrid";
        heading: string | null;
        features: Array<{
          icon: string | null;
          title: string | null;
          body: string | null;
        }> | null;
      }
    | {
        _key: string;
        _type: "hero";
        heading: string | null;
        subheading: string | null;
        ctaLabel: string | null;
        ctaHref: string | null;
        image: {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
      }
    | {
        _key: string;
        _type: "pricing";
        heading: string | null;
        plans: Array<{
          name: string | null;
          price: string | null;
          interval: string | null;
          features: Array<string> | null;
          highlighted: boolean | null;
          ctaLabel: string | null;
          ctaHref: string | null;
        }> | null;
      }
    | {
        _key: string;
        _type: "testimonial";
        heading: string | null;
        testimonials: Array<{
          quote: string | null;
          author: string | null;
          role: string | null;
          avatar: {
            asset?: {
              _ref: string;
              _type: "reference";
              _weak?: boolean;
              [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
            };
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: "image";
          } | null;
        }> | null;
      }
  > | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "siteConfig"][0] {\n    ...,\n    nav[] {\n      ...,\n    }\n  }\n': SITE_CONFIG_QUERYResult;
    '\n  *[_type == "page" && defined(slug.current)]{\n    "slug": slug.current\n  }\n': ALL_PAGE_SLUGS_QUERYResult;
    '\n  *[_type == "page" && slug.current == $slug][0] {\n    title,\n    seo,\n    blocks[] {\n      ...,\n      _type == "hero" => {\n        heading,\n        subheading,\n        ctaLabel,\n        ctaHref,\n        image,\n      },\n      _type == "featureGrid" => {\n        heading,\n        features[] {\n          icon,\n          title,\n          body,\n        }\n      },\n      _type == "pricing" => {\n        heading,\n        plans[] {\n          name,\n          price,\n          interval,\n          features,\n          highlighted,\n          ctaLabel,\n          ctaHref\n        }\n      },\n      _type == "faq" => {\n        heading,\n        items[] {\n          question,\n          answer\n        }\n      },\n      _type == "testimonial" => {\n        heading,\n        testimonials[] {\n          quote,\n          author,\n          role,\n          avatar\n        }\n      }\n    }\n  }\n': PAGE_QUERYResult;
  }
}
